WindowManager:
    MainWindow:
    Term1Window:
    Term2Window:
    Term3Window:
# Term 1 Windows
    T1W1Window:
    T1W2Window:
    T1W3Window:
    T1W4Window:
    T1W5Window:
    T1W6Window:
    T1W7Window:
    T1W8Window:
    T1W9Window:
    T1W10Window:
    T1W11Window:
    T1W12Window:
    T1W13Window:
    T1W14Window:
# Term 2 Windows
    T2W1Window:
    T2W2Window:
    T2W3Window:
    T2W4Window:
    T2W5Window:
    T2W6Window:
    T2W7Window:
    T2W8Window:
    T2W9Window:
    T2W10Window:
    T2W11Window:
    T2W12Window:
# Term 3 Windows
    T3W1Window:
    T3W2Window:
    T3W3Window:
    T3W4Window:
    T3W5Window:
    T3W6Window:
    T3W7Window:
    T3W8Window:
    T3W9Window:
    T3W10Window:
    T3W11Window:
    T3W12Window:
# -----------------------------BORDER----------------------------- #
# Main Screens
<MainWindow>:
    name: "main"
    canvas:
        Rectangle: 
            source: "images/location.jpg"
            pos: self.pos
            size: self.size
    GridLayout:
        padding: "10dp",0,"10dp",0       
        spacing: "5dp"
        cols: 3
        Image:
            source: "images/WSA.png"
        Label:
            text: "Assembly App"
            bold: True
            font_size: 30
        Image:
            source:"images/WSA.png"
        Button: 
            spacing: "10dp", "10dp", "10dp", "10dp"
            bold: True
            text: "Term 1"
            font_size: 30
            background_color: 0.39, 1.45, 2.45, 0.8
            on_release:
                app.root.current = "term1"
                root.manager.transition.direction = "left"
        Button:
            spacing: "10dp", "10dp", "10dp", "10dp"
            bold: True
            text: "Term 2"
            font_size: 30
            background_color: 0.39, 1.45, 2.45, 0.8
            on_release:
                app.root.current = "term2"
                root.manager.transition.direction = "left"
        Button: 
            spacing: "10dp", "10dp", "10dp", "10dp"
            bold: True
            text: "Term 3"
            font_size: 30
            background_color: 0.39, 1.45, 2.45, 0.8
            on_release:
                app.root.current = "term3"
                root.manager.transition.direction = "left"
        Label:
        Label:
        Label:
            font_size: 10
            text:"2023 Year 9B1"
        
<Term1Window>:
    name: "term1"
    canvas:
        Rectangle: 
            source: "images/location.jpg"
            pos: self.pos
            size: self.size
    BoxLayout:
        spacing: "5dp"
        padding: 10,10,10,10
        orientation: "vertical"
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "main"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1"
                bold: True
                font_size: 30
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text:"Week 1"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W1"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 2"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W2"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 3"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W3"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 4"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W4"
                    root.manager.transition.direction = "left"
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text:"Week 5"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W5"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 6"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W6"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 7"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W7"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 8"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W8"
                    root.manager.transition.direction = "left"
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text:"Week 9"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W9"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 10"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W10"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 11"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W11"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 12"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W12"
                    root.manager.transition.direction = "left"

        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text:"Week 13"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W13"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 14"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T1W14"
                    root.manager.transition.direction = "left"
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
<Term2Window>:
    name: "term2"
    canvas:
        Rectangle: 
            source: "images/location.jpg"
            pos: self.pos
            size: self.size
    BoxLayout:
        spacing: "5dp"
        padding: 10,10,10,10
        orientation: "vertical"
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 0.8
                on_release:
                    app.root.current = "main"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2"
                bold: True
                font_size: 30
        BoxLayout:
            spacing: "5dp"
            Button:
                text:"Week 1"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W1"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 2"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W2"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 3"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W3"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 4"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W4"
                    root.manager.transition.direction = "left"
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text:"Week 5"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W5"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 6"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W6"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 7"
                font_size: 20
                background_color: 0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current: "T2W7"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 8"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W8"
                    root.manager.transition.direction = "left"
            
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text:"Week 9"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W9"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 10"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W10"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 11"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W11"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 12"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T2W12"
                    root.manager.transition.direction = "left"
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
<Term3Window>:
    name: "term3"   
    canvas:
        Rectangle: 
            source: "images/location.jpg"
            pos: self.pos
            size: self.size 
    BoxLayout:
        spacing: "5dp"
        padding: 10,10,10,10
        orientation: "vertical"
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "main"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3"
                bold: True
                font_size: 30
        BoxLayout:
            spacing: "5dp"
            Button:
                text:"Week 1"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W1"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 2"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W2"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 3"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W3"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 4"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W4"
                    root.manager.transition.direction = "left"
        BoxLayout:
            orientation:"horizontal"
            spacing: "5dp"
            Button:
                text:"Week 5"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W5"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 6"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W6"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 7"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W7"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 8"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W8"
                    root.manager.transition.direction = "left"
            
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text:"Week 9"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W9"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 10"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W10"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 11"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W11"
                    root.manager.transition.direction = "left"
            Button:
                text:"Week 12"
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
                on_release:
                    app.root.current = "T3W12"
                    root.manager.transition.direction = "left"
        BoxLayout:
            spacing: "5dp"
            orientation:"horizontal"
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
            Button:
                text:""
                font_size: 20
                background_color:0.39, 1.45, 2.45, 0.9
# -----------------------------BORDER----------------------------- #
# Term 1 Windows
<T1W1Window>:
    name: "T1W1"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 1"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W2Window>:
    name: "T1W2"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 2"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6

<T1W3Window>:
    name: "T1W3"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 3"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W4Window>:
    name: "T1W4"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 4"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W5Window>:
    name: "T1W5"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 5"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W6Window>:
    name: "T1W6"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 6"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W7Window>:
    name: "T1W7"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 7"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W8Window>:
    name: "T1W8"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 8"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W9Window>:
    name: "T1W9"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 9"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W10Window>: 
    name: "T1W10"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 10"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W11Window>:
    name: "T1W11"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 11"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W12Window>:  
    name: "T1W12"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 12"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W13Window>: 
    name: "T1W13"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 13"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T1W14Window>:  
    name: "T1W14"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term1"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 1 Week 14"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6

# Term 2 Windows
<T2W1Window>:
    name: "T2W1"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 1"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W2Window>:
    name: "T2W2"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 2"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W3Window>:
    name: "T2W3"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 3"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W4Window>:
    name: "T2W4"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 4"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W5Window>:
    name: "T2W5"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 5"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W6Window>:
    name: "T2W6"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 6"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W7Window>:
    name: "T2W7"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 7"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W8Window>:
    name: "T2W8"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 8"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W9Window>:
    name: "T2W9"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 9"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W10Window>: 
    name: "T2W10"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 10"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W11Window>:
    name: "T2W11"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 11"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T2W12Window>:  
    name: "T2W12"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term2"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 2 Week 12"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6

# Term 3 Windows
<T3W1Window>:
    name: "T3W1"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 1"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W2Window>:
    name: "T3W2"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 2"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W3Window>:
    name: "T3W3"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 3"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W4Window>:
    name: "T3W4"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 4"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W5Window>:
    name: "T3W5"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 5"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W6Window>:
    name: "T3W6"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 6"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W7Window>:
    name: "T3W7"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 7"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W8Window>:
    name: "T3W8"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 8"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W9Window>:
    name: "T3W9"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 9"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W10Window>:
    name: "T3W10"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 10"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W11Window>:
    name: "T3W11"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 11"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6
<T3W12Window>:
    name: "T3W12"
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "< Back"
                bold: True
                background_color: 0,0,0,1
                font_size: 30
                on_release:
                    app.root.current = "term3"
                    root.manager.transition.direction = "right"
            Image:
                source: "images/WSA.png"
            Label:
                text: "Term 3 Week 12"
                font_size: 30
                bold: True
        BoxLayout:
            orientation:"horizontal"
            Button:
                text: "Year Group"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Topic"
                old: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Hosts"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
            Button:
                text: "Presenters"
                bold: True
                font_size: 30
                background_color: 0.39, 1.45, 2.45, 1
        BoxLayout:
            orientation:"horizontal"
            Button:
                font_size:30
                text: "Year 9"
                background_color: 2.55, 2.55, 2.55, 1 #White
                color: 0,0,0,1
            TextInput:
                text: root.topicY9
            TextInput:
                text: root.hostY9
            TextInput:
                text: root.presenterY9
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 8"
                color: 0,0,0,1
            TextInput:
                text: root.topicY8
            TextInput:
                text: root.hostY8
            TextInput:
                text: root.presenterY8
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 7"
                color: 0,0,0,1
            TextInput:
                text: root.topicY7
            TextInput:
                text: root.hostY7
            TextInput:
                text: root.presenterY7
        BoxLayout:
            orientation:"horizontal"
            Button:
                background_color: 2.55, 2.55, 2.55, 1 #White
                font_size:30
                text: "Year 6"
                color: 0,0,0,1
            TextInput:
                text: root.topicY6
            TextInput:
                text: root.hostY6
            TextInput:
                text: root.presenterY6